// The two playable troublemakers. Numbers are tuned so each one plays differently:
// Kiki the macaque rules the rooftops and the air, Doro the raccoon rules the ground and the shadows.
export const CHARACTERS = {
  monkey: {
    id: 'monkey',
    name: 'Kiki',
    species: 'Japanese Macaque',
    jp: 'サル',
    tagline: 'Loud, quick and always up a tree.',
    walk: 4.3,
    run: 7.4,
    sneak: 2.2,
    jump: 7.4,
    climbKinds: ['tree', 'wall', 'pole', 'ladder'],
    climbSpeed: 3.8,
    throwRange: 15,
    throwAngle: 0.62,
    tearTime: 1.25,
    rummageTime: 1.1,
    reach: 1.55,
    noise: 1.3,
    visibility: 1.15,
    barkRadius: 11,
    barkKind: 'screech',
    heavyMult: 0.48,
    medMult: 0.86,
    radius: 0.32,
    squeeze: false,
    rummage: false,
    wash: false,
    bathe: true,
    stats: { speed: 5, climb: 5, throw: 5, stealth: 2, tear: 3, strength: 2 },
    perks: [
      'Climbs trees, walls, poles & rooftops at full speed',
      'Throws twice as far — pelt people from the treetops',
      'Ear-splitting screech makes people drop what they hold',
      'Can soak in the hot spring to cool down the town\'s alert',
    ],
    flaws: [
      'Noisy and easy to spot',
      'Too big for drains and fence gaps',
      'Struggles to drag heavy things',
    ],
  },
  raccoon: {
    id: 'raccoon',
    name: 'Doro',
    species: 'Raccoon',
    jp: 'アライグマ',
    tagline: 'Sneaky, strong little hands, lives in the drains.',
    walk: 3.9,
    run: 6.6,
    sneak: 2.7,
    jump: 5.3,
    climbKinds: ['tree', 'ladder'],
    climbSpeed: 1.7,
    throwRange: 8,
    throwAngle: 0.78,
    tearTime: 0.55,
    rummageTime: 0.5,
    reach: 1.05,
    noise: 0.65,
    visibility: 0.7,
    barkRadius: 6.5,
    barkKind: 'hiss',
    heavyMult: 0.82,
    medMult: 0.97,
    radius: 0.3,
    squeeze: true,
    rummage: true,
    wash: true,
    bathe: false,
    stats: { speed: 3, climb: 2, throw: 2, stealth: 5, tear: 5, strength: 5 },
    perks: [
      'Very sneaky — quiet steps, hard to notice',
      'Travels through the drains & squeezes under fences',
      'Rips things apart in a flash and drags heavy loot easily',
      'Rummages trash bins for random (sometimes rare!) loot',
      'Hiss makes people back away in fear',
    ],
    flaws: [
      'Slow climber — trees and ladders only',
      'Short, weak throws',
      'A bit slower on foot',
    ],
  },
};

export const HATS = {
  none: { name: 'No Hat', unlock: 'Always available' },
  strawHat: { name: 'Straw Hat', unlock: "Stash the farmer's straw hat in your hideout" },
  towel: { name: 'Onsen Towel', unlock: "Stash Grandpa's onsen towel in your hideout" },
  hachimaki: { name: 'Hachimaki Headband', unlock: 'Complete 6 tasks on any Mischief Card' },
  kitsune: { name: 'Fox Mask', unlock: 'Complete the main Mischief Card (either animal)' },
  policeCap: { name: 'Police Cap', unlock: 'Get caught by the police officer 3 times' },
  crown: { name: 'Golden Crown', unlock: 'Score 8,000 points in a single Mayhem Rush' },
  sakura: { name: 'Sakura Flower', unlock: 'Discover 20 different items for your collection' },
};
