import { createRequire } from 'node:module';
import path from 'node:path';
const require = createRequire(import.meta.url);
const pw = require('/opt/node22/lib/node_modules/playwright');
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const browser = await pw.chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto('file://' + ROOT + '/index.html');
await page.waitForFunction(() => window.__game && window.__game.scene, null, { timeout: 60000 });
await page.waitForTimeout(2500);
await page.screenshot({ path: ROOT + '/docs/title.png' });
await page.click('button[data-act="story"]');
await page.click('button[data-act="go"]');
await page.waitForFunction(() => window.__game.player, null, { timeout: 30000 });
console.log('file:// OK; errors:', errors.filter((e) => !e.includes('ERR_') && !e.includes('fonts')).join(' | ') || 'none');
await browser.close();
