// The residents of Momiji-chō: who they are, how fast they are, and what they do all day.
// Routine steps: at (poi name or [x,z]), act (pose), dur [min,max], face (yaw or poi), grab/put (own item type),
// prop (broom/net/phone/tea/beater), look (does look-arounds), hooks run by the NPC system.

export const NPC_DEFS = [
  {
    id: 'farmer',
    name: 'Farmer Tanaka',
    look: 'farmer',
    home: 'farmer',
    walk: 1.8,
    run: 5.3,
    vision: 10.5,
    fov: 1.05,
    stamina: 6.5,
    voice: 0.8,
    area: 'farm',
    lines: {
      thief: ['Dorobō! (Thief!)', 'My daikon!', 'Get back here!'],
      shoo: ['Shoo! Shoo!', 'Out of my field!'],
      spot: ['Hm? A {animal}?'],
      giveup: ['Kuso... (Darn...)', 'Next time...'],
      hit: ['Itai! (Ouch!)'],
      missing: ['Where did my {item} go?'],
      happy: ['Nice harvest this year~'],
    },
    routine: [
      { at: 'canHome', act: 'pickup', dur: [0.8, 0.8], grab: 'wateringCan' },
      { at: 'waterRow0', act: 'water', dur: [1.5, 2] },
      { at: 'waterRow1', act: 'water', dur: [1.5, 2] },
      { at: 'waterRow2', act: 'water', dur: [1.5, 2] },
      { at: 'waterRow3', act: 'water', dur: [1.5, 2] },
      { at: 'canHome', act: 'pickup', dur: [0.8, 0.8], put: 'wateringCan' },
      { at: 'scarecrow', act: 'repair', dur: [3, 4], face: [-29.5, -24], look: true, hook: 'scarecrow' },
      { at: 'well', act: 'wash', dur: [3, 4], face: [-49, -18], look: true },
      { at: 'farmerBench', seat: [-52, -12], act: 'drink', dur: [9, 13], seated: true, face: 0, prop: 'tea', look: true, nap: 0.35 },
      { at: [-38, -16.5], act: 'lookaround', dur: [3, 4], face: Math.PI, look: true },
    ],
  },
  {
    id: 'priest',
    name: 'Priest Sato',
    look: 'priest',
    home: 'priest',
    walk: 1.6,
    run: 4.9,
    vision: 11,
    fov: 1.1,
    stamina: 5.5,
    voice: 0.95,
    area: 'shrine',
    lines: {
      thief: ['That belongs to the kami!', 'Stop, little thief!'],
      shoo: ['Please, not in the shrine!', 'Shoo...'],
      spot: ['Oh? A {animal} at the shrine...'],
      giveup: ['Namu... (sigh)', 'Such a naughty creature.'],
      hit: ['Oof!'],
      missing: ['Hmm, the {item} is missing...'],
      happy: ['A peaceful day.'],
    },
    routine: [
      { at: 'leafA', act: 'sweep', dur: [10, 13], prop: 'broom', face: Math.PI, look: true, hook: 'sweepA' },
      { at: 'offering', act: 'tidy', dur: [3, 4], face: -Math.PI / 2, hook: 'offering' },
      { at: 'bell', act: 'pray', dur: [4, 5], face: Math.PI, hook: 'ringBell' },
      { at: 'leafB', act: 'sweep', dur: [10, 13], prop: 'broom', face: [9, -40.5], look: true, hook: 'sweepB' },
      { at: 'torii', act: 'lookaround', dur: [4, 5], face: 0, look: true },
      { at: 'omikuji', act: 'tidy', dur: [4, 5], face: Math.PI, hook: 'omikuji' },
      { at: 'priestBench', seat: [-10.5, -41.5], act: 'sit', dur: [7, 10], seated: true, face: 0, look: true },
    ],
  },
  {
    id: 'fishmonger',
    name: 'Fishmonger Goro',
    look: 'fishmonger',
    home: 'fishmonger',
    walk: 2.0,
    run: 6.0,
    vision: 10,
    fov: 1.0,
    stamina: 5,
    voice: 0.7,
    area: 'shotengai',
    loud: true,
    lines: {
      thief: ['OI! My fish!', 'Dorobō! Thief!!', 'Come back with that!'],
      shoo: ['Scram! No freebies!', 'Go on, get!'],
      spot: ['Eh? A {animal}?!'],
      giveup: ['Tch! Fast little...', 'Grr... next time!'],
      hit: ['Oi!!'],
      missing: ["Where's my {item}?!"],
      happy: ['Irasshaimase~! Fresh fish!'],
    },
    routine: [
      { at: 'fishmonger', act: 'tidy', dur: [6, 9], face: Math.PI / 2, look: true },
      { at: 'fishShout', act: 'shout', dur: [3, 4], face: Math.PI / 2, hook: 'irasshai' },
      { at: 'fishmonger', act: 'tidy', dur: [5, 8], face: Math.PI / 2, look: true },
      { at: 'chatFish', act: 'chat', dur: [6, 8], face: 0, look: true },
      { at: 'fishBreak', act: 'stretch', dur: [5, 7], face: Math.PI / 2, look: true },
    ],
  },
  {
    id: 'dango',
    name: 'Dango Hanae',
    look: 'dango',
    home: 'dango',
    walk: 1.7,
    run: 4.8,
    vision: 10,
    fov: 1.05,
    stamina: 4.5,
    voice: 1.2,
    area: 'shotengai',
    lines: {
      thief: ['My lucky cat!', 'Give that back, you rascal!'],
      shoo: ['No dango for you!', 'Shoo, shoo!'],
      spot: ['Oh my, a {animal}!'],
      giveup: ['Ara ara...', 'Mou~ (Geez)'],
      hit: ['Kyaa!'],
      missing: ['Has anyone seen my {item}?'],
      happy: ['Dango! Fresh dango!'],
    },
    routine: [
      { at: 'dango', act: 'pickup', dur: [0.6, 0.6], face: Math.PI / 2, grab: 'uchiwa' },
      { at: 'dangoGrill', act: 'fan', dur: [7, 9], face: Math.PI, look: true },
      { at: 'dango', act: 'tidy', dur: [4, 6], face: Math.PI / 2, put: 'uchiwa', look: true },
      { at: 'dangoBench', act: 'tidy', dur: [3, 5], face: -Math.PI / 2, look: true },
      { at: 'chatDango', act: 'chat', dur: [6, 8], face: Math.PI, look: true },
      { at: 'dango', act: 'lookaround', dur: [4, 5], face: Math.PI / 2, look: true },
    ],
  },
  {
    id: 'grandpa',
    name: 'Grandpa Jiro',
    look: 'grandpa',
    home: 'bath',
    walk: 1.3,
    run: 3.9,
    vision: 8,
    fov: 1.0,
    stamina: 3.5,
    voice: 0.65,
    area: 'onsen',
    lines: {
      thief: ['Hey! That\'s my {item}!', 'Young rascal!'],
      shoo: ['Out of my bath!', 'Go soak somewhere else!'],
      spot: ['Is that... a {animal}?'],
      giveup: ['My back... ohh...', 'Hmph. Kids these days.'],
      hit: ['Gah!'],
      missing: ['Where\'s my {item}...?'],
      happy: ['Ahh... gokuraku, gokuraku~ (Paradise)'],
      bath: ['Saru da! (A monkey!) Not again!'],
    },
    routine: [
      { at: 'bath', act: 'bathe', dur: [26, 34], face: -2.3, look: true, bath: true, nap: 0.3 },
      { at: 'onsenBench', act: 'drink', dur: [6, 7], face: 0, grab: 'coffeeMilk', seated: false, look: true },
      { at: 'onsenBench', act: 'pickup', dur: [0.6, 0.6], put: 'coffeeMilk' },
      { at: 'onsenStretch', act: 'stretch', dur: [7, 9], face: Math.PI / 2, look: true },
    ],
  },
  {
    id: 'grandma',
    name: 'Grandma Hanako',
    look: 'grandma',
    home: 'grandma',
    walk: 1.4,
    run: 4.3,
    vision: 11.5,
    fov: 1.25,
    stamina: 4,
    voice: 1.35,
    area: 'grandma',
    vigilant: true,
    lines: {
      thief: ['My laundry!', 'Kora! Put that down!'],
      shoo: ['Shoo! Go on!', 'Not in my garden!'],
      spot: ['Ara? A {animal}...'],
      giveup: ['Ara ara... my knees.', 'Such a pest!'],
      hit: ['Ara!'],
      missing: ['Now where did my {item} go?'],
      happy: ['What lovely weather.'],
    },
    routine: [
      { at: 'grandma', act: 'drink', dur: [10, 14], seated: true, face: 0, prop: 'tea', look: true },
      { at: 'laundry', act: 'repair', dur: [5, 7], face: Math.PI, look: true, hook: 'laundry' },
      { at: 'futon', act: 'beat', dur: [5, 6], face: Math.PI, prop: 'beater', hook: 'futonBeat' },
      { at: 'bonsai', act: 'tidy', dur: [4, 5], face: Math.PI, look: true },
      { at: 'koi', act: 'tidy', dur: [4, 6], face: Math.PI, look: true, hook: 'feedKoi' },
      { at: 'grandmaSweep', act: 'sweep', dur: [5, 7], prop: 'broom', face: 0, look: true },
    ],
  },
  {
    id: 'salary',
    name: 'Mr. Suzuki',
    look: 'salary',
    home: 'salaryBench',
    walk: 1.9,
    run: 5.8,
    vision: 9,
    fov: 0.95,
    stamina: 5,
    voice: 0.9,
    area: 'busstop',
    lines: {
      thief: ['My briefcase! The reports!', 'Hey! Give that back!'],
      shoo: ['Not today, please.', 'Shoo, I have a meeting...'],
      spot: ['Is that a {animal}?'],
      giveup: ["I'm going to be late...", 'Haa... (sigh)'],
      hit: ['Ow!'],
      missing: ['Where is my {item}?!'],
      happy: ['Hai, hai, sou desu ne... (on the phone)'],
      missed: ['MATTE!! (WAIT!!)', 'My bus!!'],
    },
    routine: [
      { at: 'salaryBench', seat: [14.3, 5.75], act: 'read', dur: [11, 14], seated: true, face: Math.PI, grab: 'newspaper', put: 'newspaper', look: false },
      { at: 'salaryStop', act: 'lookaround', dur: [4, 5], face: Math.PI / 2, look: true },
      { at: 'salaryPhone', act: 'phone', dur: [7, 9], face: Math.PI, prop: 'phone', look: false, hook: 'phone' },
      { at: 'salaryVend', act: 'tidy', dur: [2.5, 3], face: 0, hook: 'buyCoffee' },
      { at: 'salaryStop', act: 'lookaround', dur: [4, 6], face: Math.PI / 2, look: true },
    ],
  },
  {
    id: 'officer',
    name: 'Officer Kobayashi',
    look: 'officer',
    home: 'officer',
    walk: 1.7,
    run: 6.0,
    vision: 12,
    fov: 1.1,
    stamina: 7.5,
    voice: 0.85,
    area: 'shotengai',
    officer: true,
    lines: {
      thief: ['Stop right there!', 'Halt! Police!'],
      shoo: ['Move along, little one.', 'No loitering!'],
      spot: ['A {animal} on the loose...'],
      giveup: ['I\'ll get you next time.', 'Slippery critter...'],
      hit: ['Assaulting an officer?!'],
      missing: ['Hmm.'],
      happy: ['All quiet in Momiji-chō.'],
      caught: ['Gotcha! Back to the woods with you!'],
    },
    routine: [
      { at: 'officer', act: 'lookaround', dur: [8, 11], face: -Math.PI / 2, look: true, prop: 'net' },
      { at: [0, -30], act: 'lookaround', dur: [2, 3], face: 0, look: true, prop: 'net' },
      { at: [-1, -6], act: 'lookaround', dur: [1.5, 2], face: 0, look: true, prop: 'net' },
      { at: [-24, -5.2], act: 'lookaround', dur: [2, 3], face: Math.PI, look: true, prop: 'net' },
      { at: [-8, 4.2], act: 'lookaround', dur: [2, 3], face: Math.PI, look: true, prop: 'net' },
      { at: [20, 5.2], act: 'lookaround', dur: [2, 3], face: 0, look: true, prop: 'net' },
      { at: [26, -5.8], act: 'lookaround', dur: [2, 3], face: Math.PI, look: true, prop: 'net' },
    ],
  },
];
